# Odometry configuration (15 elements)
odom0: odom
odom0_config: [true, true, false, 
                false, false, true, 
                false, false, false, 
                false, false, false, 
                false, false, false]

# IMU configuration (15 elements)
imu0: imu
imu0_config: [false, false, false, 
              true, true, true, 
              false, false, false, 
              false, false, false, 
              false, false, false]

process_noise_covariance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 
                           0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 
                           0.01, 0.01, 0.01]