#----------------------------- OCCUPANCY MAP PARAMS

sensor_input_mode: 0 # 0 camera 1: lidar
localization_mode: 1 # 0: pose (default) 1: odom
depth_image_topic: /camera/depth/image_raw
pose_topic: /mavros/local_position/pose
odom_topic: /mavros/local_position/odom
# depth_image_topic: /camera/depth/image_rect_raw
aligned_depth_image_topic: /camera/aligned_depth_to_color/image_raw

# robot size
robot_size: [0.5, 0.5, 0.3]

# Camera Parameters
depth_intrinsics: [554.254691191187, 554.254691191187, 320.5, 240.5] # fx,  fy, cx, cy
depth_scale_factor: 10 # 1000 for Intel Realsense Camera
depth_min_value: 0.5
depth_max_value: 5.0
depth_filter_margin: 2 # filter
depth_skip_pixel: 2 # filter
image_cols: 640
image_rows: 480
body_to_camera: [0.0,  0.0,  1.0,  0.09,
                -1.0,  0.0,  0.0,  0.0 ,   
                 0.0, -1.0,  0.0,  0.095,
                 0.0,  0.0,  0.0,  1.0]
color_intrinsics: [604.404296875, 604.404296875, 325.03704833984375, 245.77059936523438] # intel realsense
body_to_camera_color: [0.0,  0.0,  1.0,  0.065,
                      -1.0,  0.0,  0.0,  0.025,   
                       0.0, -1.0,  0.0,  0.12,
                       0.0,  0.0,  0.0,  1.0]

# Raycasting
raycast_max_length: 5.0
p_hit: 0.70
p_miss: 0.35
p_min: 0.12
p_max: 0.97
p_occ: 0.80


# Map
map_resolution: 0.1
ground_height: -0.1 # m
map_size: [40, 40, 3] # meter. in x y z direction (reserved size)
local_update_range: [5, 5, 5]
local_bound_inflation: 3.0 # inflate local bound in meter
clean_local_map: false

# visualziation
local_map_size: [40, 40, 6] # meter. in x y z direction (only for visualization)
max_height_visualization: 2.5 # m
visualize_global_map: true
verbose: false

prebuilt_map_directory: "No"
# prebuilt_map_directory: "/home/cerlab/map/static_map.pcd"

#--------------------------------------------- DETECTOR PARAMS

# time difference
time_difference: 0.033

# sensor data processing
voxel_occupied_thresh: 15 # min num of points for a voxel to be occupied in voxel filter

# dbscan
dbscan_min_points_cluster: 10 # 20: 4.0m range; 30: 3.5m range 40: 3.0m range
dbscan_search_range_epsilon: 0.1 # searching range radius

# bounding box filtering
filtering_BBox_IOU_threshold: 0.05
yolo_overwrite_distance: 3

# tracking and data association
history_size: 100 # size of tracking history. history[0] is current detection
similarity_threshold: 0.02 # similiary threshold for data association matching comparison
fix_size_history_threshold: 10 # History threshold (num of frames) to fix box size
fix_size_dimension_threshold: 0.4 # dimension threshold (size of proportional) to fix box size

e_p: 0.25
e_q_pos: 0.01
e_q_vel: 0.05
e_q_acc: 0.05
e_r_pos: 0.04
e_r_vel: 0.3
e_r_acc: 0.6

kalman_filter_averaging_frames: 10

# classification
frame_skip: 5 # num of frames skiped when comparing 2 point clouds
dynamic_velocity_threshold: 0.15
dynamic_voting_threshold: 0.8
maximum_skip_ratio: 0.5 # the upper limit of points that are skipped(out of previous FOV) to be classfified as dynamic
frames_force_dynamic: 10 # Range of searching dynamic obstacles in box history
frames_force_dynamic_check_range: 30 # threshold for forcing dynamic obstacles
dynamic_consistency_threshold: 1 # obstacles being voted as dynamic for continuous k frames are eligible to be classified as dynamic

# constrain size
constrain_size: true
target_object_size: [0.5, 0.5, 1.7]


