# Parameters for the fuzzy_controller_node

num_samples: 20          # Number of samples along the Bezier curve
threshold: 0.005         # Distance (in meters) to consider a waypoint reached
rate: 10                 # Control loop rate (Hz)
initial_velocity: 0.0001 # Initial robot velocity (m/s)
